version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=writeinpeace
      - POSTGRES_USER=israel
      - POSTGRES_PASSWORD=isra321
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
